# Default values for fleet-mgmt-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: default 
db:
  name: db
  mongodb_url: mongodb://db:27017/gps-db
  image: mongo
  port: 27017
gps:
  name: gps
  binary_server_uri: http://binary-server:7001/telemetry
  telemetry_name: Helm_Kubernetes
  image: nwrightnz/gps-sim
binaryserver:
  name: binary-server
  port: 7001
  cache: true
  image: nwrightnz/gps-binary-server
dataserver:
  name: data-server
  port: 7002
  ingress_port: 80
  image: nwrightnz/gps-data-server
  hostname: ds.cloudlearning.pro
ui:
  name: gps-ui
  port: 80  
  image: nwrightnz/gps-ui
  hostname: fleet.cloudlearning.pro
  # The lat and lon below are used to center the map on the city of your choice.
  latitude:  -36.8485
  longtitude: 174.7633
replicaCount: 1
image:
  pullPolicy: IfNotPresent
ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  annotations:
     ingressclass: traefik 

