kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.dataserver.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.dataserver.name }}

  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.dataserver.port }}
