apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingressclass }}

spec:
  rules:
  - host: {{ .Values.ui.hostname }} 
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ui.name }}
          servicePort: {{ .Values.ui.port }}
