kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.ui.name }}

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
